In [1]:
import numpy as np

arr = np.arange(1, 10)  # Tạo mảng một chiều arr có 9 phần tử từ 1 đến 9
print(f'Mảng 1 chiều ban đầu:\n', arr)

grid = arr.reshape((3, 3))  # Chuyển đổi mảng arr thành mảng 2 chiều 3x3

print(f'Mảng 2 chiều sau khi reshape:\n', grid)


Mảng 1 chiều ban đầu:
 [1 2 3 4 5 6 7 8 9]
Mảng 2 chiều sau khi reshape:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
