In [1]:
import numpy as np
x = np.array([1, 2, 3]) 
y = np.array([4, 5, 6]) 
np.concatenate([x,y]) #Kết hợp ma trận x, y 

array([1, 2, 3, 4, 5, 6])

In [3]:
np.concatenate([x,y], axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [4]:
import numpy as np 
a = np.array([[1, 2], 
              [3, 4]]) 
b = np.array([[5, 6], 
              [7, 8]]) 
# Kết hợp theo chiều đầu tiên (trục dọc/ trục 0) của mảng 
np.concatenate((a, b))  


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
np.concatenate([a,b], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])