In [1]:
import numpy as np
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [ ]:
x[np.newaxis, :] # tao ma tran 1x3 su dung np.newaxis()

array([[1, 2, 3]])

In [3]:
np.newaxis is None

True

In [4]:
y=x[np.newaxis, :]
print(f'ma tran x ban dau: ', x)
print('ma tran y sau khi them hang: ', y)


ma tran x ban dau:  [1 2 3]
ma tran y sau khi them hang:  [[1 2 3]]


In [7]:
z=x[:,np.newaxis, :]
print('ma tran x ban dau:', x)
print('ma tran z sau khi them cot:\n', z)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [8]:
x

array([1, 2, 3])

In [9]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [10]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [ ]:
np.ndim(x) # kiem tra so chieu cua mang x sau khi reshape

1

In [12]:
np.ndim(x.reshape((3, 1)))

2