In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5]) 
sorted_arr = np.sort(arr) 
 
sorted_arr 

array([1, 2, 3, 4, 5])

In [2]:
arr = np.array([1, 2, 3, 4, 5]) 
arr.sort() 
 
arr

array([1, 2, 3, 4, 5])

In [3]:
arr = np.array([3, 1, 4, 2, 5]) 
sorted_arr_descending= np.sort(arr)[::-1] 
 
sorted_arr_descending

array([5, 4, 3, 2, 1])

In [4]:
arr = np.array([3, 1, 4, 2, 5]) 
arr.sort()                   
 
arr[::-1]

array([5, 4, 3, 2, 1])