In [1]:
!python -m pip install --upgrade pip 
!python -m pip install numpy


   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 621.8 kB/s eta 0:00:02
   ----------- ---------------------------- 0.5/1.8 MB 621.8 kB/s eta 0:00:02
   ----------------- ---------------------- 0.8/1.8 MB 602.6 kB/s eta 0:00:02
   ----------------- ---------------------- 0.8/1.8 MB 602.6 kB/s eta 0:00:02
   ----------------------- ---------------- 1.0/1.8 MB 625.3 kB/s eta 0:00:02
   ----------------------- ---------------- 1.0/1.8 MB 625.3 kB/s eta 0:00:02
   ----------------------------- ---------- 1.3/1.8 MB 610.6 kB/s eta 0:00:01
   ----------------------------- ---------- 1.3/1.8 MB 610.6 kB/s eta 0:00:01
   ----------------------------------- ---- 1.6/1.8 MB 621.3 kB/s eta 0:00:01
   -------------------

In [2]:
import numpy as np 

In [3]:
np.__version__ 

'2.3.4'

In [4]:
arr = np.array([1.5, 2.7, 3.2])
arr


array([1.5, 2.7, 3.2])

In [5]:
arr.dtype 

dtype('float64')

In [ ]:

arr_int = arr.astype(np.int32)
print(arr_int, arr_int.dtype)


[1 2 3] int32


In [10]:
print(arr, arr.dtype)

[1.5 2.7 3.2] float64
