In [2]:
import numpy as np
np.zeros(5,dtype=int)


array([0, 0, 0, 0, 0])

In [3]:
al=np.ones((3,3),dtype=float)
al

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
al.dtype 

dtype('float64')

In [5]:
import numpy as np
np.full((5,5),100,dtype=float)


array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [6]:
import numpy as np
arr_1 = np.arange(10)
print(arr_1)


[0 1 2 3 4 5 6 7 8 9]


In [8]:
import numpy as np
arr_2 =np.arange(5, 15, 2)
print(arr_2)


[ 5  7  9 11 13]


In [9]:
import numpy as np
arr_1 = np.linspace(0, 15, 5)
print(arr_1)


[ 0.    3.75  7.5  11.25 15.  ]


In [ ]:
arr_2 = np.linspace(0, 1, 10)

In [10]:
import numpy as np
arr_5 = np.random.random(5)
print(arr_5)

[0.43552227 0.89086678 0.53909918 0.81327086 0.14392724]


In [11]:
import numpy as np
arr_7 = np.random.randint(0,10,(3,3))
print(arr_7)

[[0 0 9]
 [5 0 5]
 [8 8 7]]


In [12]:
######### tao ma tran don vi 3x3
import numpy as np
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])