In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[3 6 9]
Hàng đầu tiên của mảng arr là: [1 2 3]
Cột đầu tiên của mảng arr là: [1 4 7]


In [ ]:
print("Cot dau tien cua mang arr la: ", arr[: ,0]) # lay tat ca cac hang cua cot 0
print("Hang dau tien cua mang arr la: ", arr[0, :]) 
print("Hang dau tien cua mang arr la: ", arr[0])

Cot dau tien cua mang arr la:  [1 4 7]
Hang dau tien cua mang arr la:  [1 2 3]
Hang dau tien cua mang arr la:  [1 2 3]
