In [1]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
arr_1 = np.array(my_list)
print(arr_1)

[1 2 3 4 5]


In [2]:
arr_1.dtype 

dtype('int64')

In [3]:
arr_2=np.array([my_list], dtype=float)
arr_2 

array([[1., 2., 3., 4., 5.]])

In [4]:
arr_2.dtype 

dtype('float64')

In [5]:
# tao mang tu dnnh sach
my_tuple=(1,2,3,4,5)
arr_3=np.array(my_tuple)
arr_3 

array([1, 2, 3, 4, 5])

In [6]:
arr_3.dtype

dtype('int64')

In [7]:
#####################Tao numpy array tu mang hai chieu 
arr_4=np.array([(1,2,3),(4,5,6)])
arr_4 

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr_4.dtype 

dtype('int64')