In [2]:
import numpy as np
arr_2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7 ,8, 9]])
arr_view = arr_2d[:2, :2]
print(arr_view)

[[1 2]
 [4 5]]


In [ ]:
# thay doi gia tri trong view
arr_view[0, 0] = 100 # chinh sua phan tu
print(arr_view)
print(arr_2d)

[[100   2]
 [  4   5]]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
